### ISSUE TITLE
[1.0.0.8] Spelling / Key Mistakes - Adapter Truststore / Router Env Variables

### ISSUE THREAD

**Issue by naamancampbell** [wso2/kubernetes-microgateway#79]
**Description:**
Spelling/key mistakes in `adapter-deployment.yaml` and `gateway-runtime-deployment.yaml` cause the following issues:

- unable to specify user-generated certificates in `wso2.deployment.adapter.security.truststore`
- env variables specified in `wso2.deployment.gatewayRuntime.router.envOverride` are ignored

**Suggested Labels:**
- bug

**Affected Product Version:**

Affects master commit id [6647d52](https://github.com/wso2/kubernetes-microgateway/commit/6647d520eea928e80fc0a615470430cbcc11726f)

**Comment by renuka-fernando** [comment]
Fixed with #80
