### ISSUE TITLE
Document changes requested for readme.md

### ISSUE THREAD

**Issue by chamindi-a** [wso2/kubernetes-microgateway#8]
**Description**:
Need to change the document with the suggested listed below

**Steps to reproduce**:
1. Open https://github.com/wso2/kubernetes-microgateway/blob/master/helm/microgateway/README.md

**Issue**:
 Please see to change the following at your earliest:
1. There is a mention of Identity Server in this document please correct it 
2. Search for 'An already setup Kubernetes cluster' and change the link to the right one.

**Comment by Aaquiff** [comment]
Create #9 to fix this.

**Comment by chamindi-a** [comment]
This issues is closed with this PR https://github.com/wso2/kubernetes-microgateway/pull/9
